version: "3.8"

services:
  recommendation-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recommendation_system
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env
    # Remove volume mount for production stability
    # volumes:
    #   - ./app:/app/app:ro  # Read-only mount for development
    networks:
      - recommendation_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits for stability
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"

networks:
  recommendation_network:
    driver: bridge
