services:
  db:
    image: postgres:latest
    container_name: online_coding_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hihi12345
      POSTGRES_DB: occs_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network

volumes:
  db_data:
networks:
  db_network: